Update learn-github-actions.yml
disabled flow-check

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -5,35 +5,39 @@ on:
     branches:
       - main
 jobs:
-  flow-check:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+#   flow-check:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 14
+#       - name: Install Node.js
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 14
+#       - name: Init env file
+#         run: echo "need_build=true" >> "$GITHUB_ENV"
 
-      - name: Run Flow
-        run: |
-          git fetch --unshallow
-          if git diff --name-only ${{ github.sha }} ${{ github.sha }}^ | grep -qE '\.js$'; then
-            yarn install
-            npm run 
-            flowflowStatus=$?
-            if [ $flowStatus -ne 0 ]; then
-              echo "Flow check failed. Exiting..."
-              exit 1
-            fi
-          else
-            echo "No JavaScript files changed. Skipping Flow check."
-              exit 1
-          fi
+#       - name: Run Flow
+#         run: |
+#           git fetch --unshallow
+#           if git diff --name-only ${{ github.sha }} ${{ github.sha }}^ | grep -qE '\.js$'; then
+#             yarn install
+#             npm run 
+#             flowflowStatus=$?
+#             if [ $flowStatus -ne 0 ]; then
+#               echo "Flow check failed. Exiting..."
+#               exit 1
+#             fi
+#           else
+#             echo "No JavaScript files changed. Skipping Flow check."
+#             echo "need_build=false" >> "$GITHUB_ENV"
+#             exit 1
+#           fi
 
   build:
     runs-on: ubuntu-latest
+#     if: "${{ env.need_build == true }}"
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
